title: Project
preset: pages

status:
  draft: Draft
  listed: Published

fields:
  date:
    type: date
    default: today
    required: true
    width: 1/2
  categories:
    label: Categories
    type: multiselect
    min: 1
    required: true
    width: 1/2
    options:
      identities: Identities
      publications: Publications
      web: Web
      ephemera: Ephemera
  works:
    label: Works
    type: structure
    required: true
    fields:
      title:
        label: Name
        help: Used for reference and for the image alt text
        type: text
      image:
        label: Image
        type: files
        template: image
        required: true
        max: 1
      width:
        label: Image width
        type: select
        default: full
        required: true
        options:
          full: 100%
          threeq: 75%
          half: 50%
      categories:
        label: Categories
        type: multiselect
        min: 1
        options:
          identities: Identities
          publications: Publications
          web: Web
          ephemera: Ephemera
      caption:
        label: Caption
        type: textarea
        size: small


#drafts:
#  extends: sections/works
#  label: Draft works
#
#listed:
#  extends: sections/works
#  label: Included works
#  layout: cards