title: Site

sections:
  content:
    type: pages
    template:
      - projects
      - texts
  pages: 
    type: pages
    template: default
  options:
    type: fields
    fields:
      footerLinks:
        label: External links
        type: structure
        fields:
          linkText:
            type: text
          url:
            type: text
            help: Include the https://, or for email, use mailto:cleotsw@gmail.com
      favicon:
        type: structure
        max: 1
        help: Use https://tools.rmv.fyi/tools/favicon-genny to generate PNGs from your square SVG
        fields:
          svg:
            label: SVG
            type: files
            template: image
            max: 1
          png16x:
            label: PNG 16x16
            type: files
            template: image
            max: 1
          png32x:
            label: PNG 32x32
            type: files
            template: image
            max: 1